Repository Marioespiro/Acme-Toolkit, pull requests merged in 2022-04, with the labels that each got.

#124 Patron Dashboard
  src/main/java/acme/features/patron/dashboard/PatronDashboardController.java
  src/main/java/acme/features/patron/dashboard/PatronDashboardRepository.java
  src/main/java/acme/features/patron/dashboard/PatronDashboardShowService.java
  src/main/webapp/WEB-INF/resources/sample-data/patronage.csv
  src/main/webapp/WEB-INF/views/fragments/menu-en.i18n
  src/main/webapp/WEB-INF/views/fragments/menu-es.i18n
  src/main/webapp/WEB-INF/views/fragments/menu.jsp
  src/main/webapp/WEB-INF/views/patron/patron-dashboard/form.jsp
  src/main/webapp/WEB-INF/views/patron/patron-dashboard/messages-en.i18n
  src/main/webapp/WEB-INF/views/patron/patron-dashboard/messages-es.i18n
Labels: enhancement, second deliverable

#127 Task 059 - Administrator Dashboard
  src/main/java/acme/features/administrator/dashboard/AdministratorDashboardController.java
  src/main/java/acme/features/administrator/dashboard/AdministratorDashboardRepository.java
  src/main/java/acme/features/administrator/dashboard/AdministratorDashboardShowService.java
  src/main/java/acme/forms/AdministratorDashboard.java
  src/main/webapp/WEB-INF/resources/sample-data/item.csv
  src/main/webapp/WEB-INF/views/administrator/administrator-dashboard/form.jsp
  src/main/webapp/WEB-INF/views/administrator/administrator-dashboard/messages-en.i18n
  src/main/webapp/WEB-INF/views/administrator/administrator-dashboard/messages-es.i18n
  src/main/webapp/WEB-INF/views/fragments/menu-en.i18n
  src/main/webapp/WEB-INF/views/fragments/menu-es.i18n
  src/main/webapp/WEB-INF/views/fragments/menu.jsp
Labels: enhancement, second deliverable

#136 Patron dashboard
  src/main/java/acme/features/patron/dashboard/PatronDashboardRepository.java
  src/main/java/acme/features/patron/dashboard/PatronDashboardShowService.java
  src/main/webapp/WEB-INF/views/patron/patron-dashboard/form.jsp
  src/main/webapp/WEB-INF/views/patron/patron-dashboard/messages-en.i18n
  src/main/webapp/WEB-INF/views/patron/patron-dashboard/messages-es.i18n
Labels: enhancement, priority

#134 Inventor toolkits
  src/main/java/acme/features/inventor/items/InventorComponentListService.java
  src/main/java/acme/features/inventor/items/InventorItemController.java
  src/main/java/acme/features/inventor/items/InventorItemRepository.java
  src/main/java/acme/features/inventor/items/InventorItemShowService.java
  src/main/java/acme/features/inventor/items/InventorToolListService.java
  src/main/java/acme/features/inventor/toolkits/InventorToolkitController.java
  src/main/java/acme/features/inventor/toolkits/InventorToolkitListService.java
  src/main/java/acme/features/inventor/toolkits/InventorToolkitRepository.java
  src/main/java/acme/features/inventor/toolkits/InventorToolkitShowService.java
  src/main/webapp/WEB-INF/views/fragments/menu-en.i18n
  src/main/webapp/WEB-INF/views/fragments/menu-es.i18n
  src/main/webapp/WEB-INF/views/fragments/menu.jsp
  src/main/webapp/WEB-INF/views/inventor/item/form.jsp
  src/main/webapp/WEB-INF/views/inventor/item/list.jsp
  src/main/webapp/WEB-INF/views/inventor/item/messages-en.i18n
  src/main/webapp/WEB-INF/views/inventor/item/messages-es.i18n
  src/main/webapp/WEB-INF/views/inventor/toolkit/form.jsp
  src/main/webapp/WEB-INF/views/inventor/toolkit/list.jsp
  src/main/webapp/WEB-INF/views/inventor/toolkit/messages-en.i18n
  src/main/webapp/WEB-INF/views/inventor/toolkit/messsages-es.i18n
Labels: enhancement, priority

#144 Añadido los test de authenticated sobre security configuration
  src/test/java/acme/testing/authenticated/AuthenticatedSystemConfigurationShowTest.java
  src/test/resources/authenticated/system-configuration/show.csv
Labels: enhancement

#143 Task 050/051 s3 09
  .gitignore
  src/main/java/acme/features/inventor/items/InventorComponentListService.java
  src/main/java/acme/features/inventor/items/InventorItemRepository.java
  src/main/java/acme/features/inventor/items/InventorItemShowService.java
  src/main/java/acme/features/inventor/items/InventorToolListService.java
  src/main/webapp/WEB-INF/views/fragments/menu-en.i18n
  src/main/webapp/WEB-INF/views/fragments/menu-es.i18n
  src/main/webapp/WEB-INF/views/fragments/menu.jsp
Labels: enhancement, priority

#135 All principal tookits
  src/main/java/acme/entities/toolkit/Toolkit.java
  src/main/java/acme/features/any/item/AnyComponentListService.java
  src/main/java/acme/features/any/item/AnyItemRepository.java
  src/main/java/acme/features/any/item/AnyToolListService.java
  src/main/java/acme/features/any/toolkit/AnyToolkitController.java
  src/main/java/acme/features/any/toolkit/AnyToolkitListService.java
  src/main/java/acme/features/any/toolkit/AnyToolkitRepository.java
  src/main/java/acme/features/any/toolkit/AnyToolkitShowService.java
  src/main/webapp/WEB-INF/resources/sample-data/item.csv
  src/main/webapp/WEB-INF/resources/sample-data/quantity.csv
  src/main/webapp/WEB-INF/resources/sample-data/toolkit.csv
  src/main/webapp/WEB-INF/views/any/toolkit/form.jsp
  src/main/webapp/WEB-INF/views/any/toolkit/list.jsp
  src/main/webapp/WEB-INF/views/any/toolkit/messages-en.i18n
  src/main/webapp/WEB-INF/views/any/toolkit/messages-es.i18n
  src/main/webapp/WEB-INF/views/fragments/menu-en.i18n
  src/main/webapp/WEB-INF/views/fragments/menu-es.i18n
  src/main/webapp/WEB-INF/views/fragments/menu.jsp
Labels: enhancement, priority

#150 Limpiados todos los malos olores y bugs del proyecto
  pom.xml
  src/main/java/acme/entities/patronage_reports/PatronageReport.java
  src/main/java/acme/entities/system_configurations/SystemConfiguration.java
  src/main/java/acme/features/administrator/dashboard/AdministratorDashboardShowService.java
  src/main/java/acme/features/administrator/system_configuration/AdministratorSystemConfigurationController.java
  src/main/java/acme/features/administrator/system_configuration/AdministratorSystemConfigurationRepository.java
  src/main/java/acme/features/administrator/system_configuration/AdministratorSystemConfigurationShowService.java
  src/main/java/acme/features/any/item/AnyComponentListService.java
  src/main/java/acme/features/any/item/AnyItemShowService.java
  src/main/java/acme/features/any/item/AnyToolListService.java
  src/main/java/acme/features/any/user_accounts/AnyUserAccountsController.java
  src/main/java/acme/features/any/user_accounts/AnyUserAccountsRepository.java
  src/main/java/acme/features/any/user_accounts/AnyUserAccountsShowService.java
  src/main/java/acme/features/any/user_accounts/AnyUserAccountstListService.java
  src/main/java/acme/features/authenticated/system_configuration/AuthenticatedSystemConfigurationController.java
  src/main/java/acme/features/authenticated/system_configuration/AuthenticatedSystemConfigurationRepository.java
  src/main/java/acme/features/authenticated/system_configuration/AuthenticatedSystemConfigurationShowService.java
  src/main/java/acme/features/inventor/items/InventorComponentListService.java
  src/main/java/acme/features/inventor/items/InventorItemShowService.java
  src/main/java/acme/features/inventor/items/InventorToolListService.java
  src/main/java/acme/features/inventor/patronage_report/InventorPatronageReportController.java
  src/main/java/acme/features/inventor/patronage_report/InventorPatronageReportListService.java
  src/main/java/acme/features/inventor/patronage_report/InventorPatronageReportRepository.java
  src/main/java/acme/features/inventor/patronage_report/InventorPatronageReportShowService.java
  src/main/java/acme/features/inventor/toolkits/InventorToolkitListService.java
  src/main/java/acme/features/inventor/toolkits/InventorToolkitShowService.java
  src/main/java/acme/features/patron/dashboard/PatronDashboardShowService.java
  src/main/java/acme/features/patron/patronage_report/PatronPatronageReportController.java
  src/main/java/acme/features/patron/patronage_report/PatronPatronageReportListService.java
  src/main/java/acme/features/patron/patronage_report/PatronPatronageReportRepository.java
  src/main/java/acme/features/patron/patronage_report/PatronPatronageReportShowService.java
  src/main/java/acme/forms/AdministratorDashboard.java
  src/main/java/acme/forms/PatronDashboard.java
  src/main/webapp/WEB-INF/views/administrator/administrator-dashboard/form.jsp
  src/main/webapp/WEB-INF/views/administrator/administrator-dashboard/messages-en.i18n
  src/main/webapp/WEB-INF/views/administrator/administrator-dashboard/messages-es.i18n
  src/main/webapp/WEB-INF/views/patron/patron-dashboard/form.jsp
  src/main/webapp/WEB-INF/views/patron/patron-dashboard/messages-en.i18n
  src/main/webapp/WEB-INF/views/patron/patron-dashboard/messages-es.i18n
Labels: enhancement
